// src/components/Global/FooterPages.tsx
import Image from "next/image";

type FooterPagesProps = {
  title: string;
  firstParagraph: string;
  secondParagraph: string;
  firstImageSrc: string;
  secondImageSrc: string;
  thirdImageSrc: string;
  firstImageAlt: string;
  secondImageAlt: string;
  thirdImageAlt: string;
};

export default function FooterPages({
  firstImageAlt,
  firstImageSrc,
  firstParagraph,
  secondImageAlt,
  secondImageSrc,
  secondParagraph,
  thirdImageAlt,
  thirdImageSrc,
  title,
}: FooterPagesProps) {
  return (
    <div className="flex flex-col gap-y-8">
      <div className="group/footerpagestitle flex flex-col gap-y-4">
        <h1 className="title text-center">{title}</h1>
        <div className="relative h-72 overflow-hidden rounded-3xl">
          <Image
            className="size-full rounded-3xl object-cover transition-transform duration-300 group-hover/footerpagestitle:scale-105"
            src={firstImageSrc}
            alt={firstImageAlt}
            priority
            fill
          />
        </div>
      </div>
      <div className="grid grid-cols-1 gap-8 sm:grid-cols-2">
        <div className="flex flex-col gap-y-4 rounded-3xl">
          <div className="group/footerpagesfirstparagraph relative h-56 overflow-hidden rounded-3xl md:h-72">
            <Image
              className="size-full rounded-3xl object-cover transition-transform duration-300 group-hover/footerpagesfirstparagraph:scale-105"
              src={secondImageSrc}
              alt={secondImageAlt}
              priority
              fill
            />
          </div>
          <p className="text-pretty md:text-lg">{firstParagraph}</p>
        </div>
        <div className="flex flex-col gap-y-4">
          <div className="group/footerpagessecondparagraph relative h-56 overflow-hidden rounded-3xl md:h-72">
            <Image
              className="size-full rounded-3xl object-cover transition-transform duration-300 group-hover/footerpagessecondparagraph:scale-105"
              src={thirdImageSrc}
              alt={thirdImageAlt}
              priority
              fill
            />
          </div>
          <p className="text-pretty md:text-lg">{secondParagraph}</p>
        </div>
      </div>
    </div>
  );
}

// components/FooterPages.vue
<template>
  <div class="flex flex-col gap-y-8">
    <div class="flex flex-col gap-y-4 group/footerpagestitle">
      <h1 class="text-center title">{{ title }}</h1>
      <div class="overflow-hidden h-72 rounded-3xl">
        <NuxtImg
          class="object-cover transition-transform duration-300 size-full rounded-3xl group-hover/footerpagestitle:scale-105"
          :src="firstImageSrc"
          :alt="firstImageAlt"
        />
      </div>
    </div>
    <div class="grid grid-cols-1 gap-8 sm:grid-cols-2">
      <div class="flex flex-col gap-y-4 rounded-3xl">
        <div class="h-56 overflow-hidden md:h-72 rounded-3xl group/footerpagesfirstparagraph">
          <NuxtImg
            class="object-cover transition-transform duration-300 size-full rounded-3xl group-hover/footerpagesfirstparagraph:scale-105"
            :src="secondImageSrc"
            :alt="secondImageAlt"
          />
        </div>
        <p class="md:text-lg text-pretty">
          {{ firstParagraph }}
        </p>
      </div>
      <div class="flex flex-col gap-y-4">
        <div class="h-56 overflow-hidden md:h-72 rounded-3xl group/footerpagessecondparagraph">
          <NuxtImg
            class="object-cover transition-transform duration-300 size-full rounded-3xl group-hover/footerpagessecondparagraph:scale-105"
            :src="thirdImageSrc"
            :alt="thirdImageAlt"
          />
        </div>
        <p class="md:text-lg text-pretty">
          {{ secondParagraph }}
        </p>
      </div>
    </div>
  </div>
</template>

<script setup>
defineProps({
  title: String,
  firstParagraph: String,
  secondParagraph: String,
  firstImageSrc: String,
  secondImageSrc: String,
  thirdImageSrc: String,
  firstImageAlt: String,
  secondImageAlt: String,
  thirdImageAlt: String,
});
</script>
