// src/components/Home/HomeSourceCard.tsx
import Image from "next/image";
import Link from "next/link";

type HomeSourceCardProps = {
  title: string;
  path: string;
  imageSrc: string;
  imageAlt: string;
};

export default function HomeSourceCard({
  title,
  path,
  imageSrc,
  imageAlt,
}: HomeSourceCardProps) {
  return (
    <Link
      href={path}
      className="group/homesourcecard relative min-h-72 overflow-hidden rounded-xl text-neutral-950"
      target="_blank"
      rel="noopener noreferrer"
    >
      <Image
        className="rounded-xl object-cover"
        src={imageSrc}
        alt={imageAlt}
        fill
      />
      <span className="absolute bottom-0 z-10 w-full translate-y-12 bg-primary-950/85 py-2 text-center font-pally text-xl text-neutral-50 transition-all duration-300 group-hover/homesourcecard:-translate-y-0">
        {title}
      </span>
    </Link>
  );
}

// components/HomeSourceCard.vue
<template>
  <a
    :href="path"
    class="relative overflow-hidden rounded-xl text-neutral-950 group/homesourcecard"
    target="_blank"
    rel="noopener noreferrer"
  >
    <NuxtImg class="object-cover size-full rounded-xl" :src="imageSrc" />
    <span
      class="absolute bottom-0 z-10 w-full py-2 text-xl text-center transition-all duration-300 translate-y-12 bg-primary-950/85 font-pally text-neutral-50 group-hover/homesourcecard:-translate-y-0"
    >
      {{ title }}</span
    >
  </a>
</template>

<script setup>
defineProps({
  title: String,
  path: String,
  imageSrc: String,
});
</script>
