// src/components/Home/HomeHero.tsx
import React from "react";
import Image from "next/image";
import { HomeHeroDataProps } from "@/constants/type";

export default function HomeHero({
  title,
  subtitle,
  imageSrc,
  imageAlt,
}: HomeHeroDataProps) {
  return (
    <div className="group/plantation relative h-[50vh] w-full overflow-hidden rounded-3xl">
      <div className="absolute left-1/2 top-1/2 z-[1] flex -translate-x-1/2 -translate-y-1/2 flex-col gap-y-2 max-sm:w-full max-sm:p-5 sm:gap-y-4">
        <h1 className="font-pally text-4xl font-medium text-neutral-50 lg:max-w-[46.5rem] lg:text-6xl">
          <span className="text-primary-200">{title.split(" ")[0]}</span>{" "}
          {title.split(" ").slice(1).join(" ")}
        </h1>
        <p className="text-lg text-neutral-50 lg:max-w-[41.5rem] lg:text-xl">
          {subtitle}
        </p>
      </div>
      <Image
        className="size-full rounded-3xl object-cover brightness-[0.45] transition-transform duration-300 group-hover/plantation:scale-105"
        width="1336"
        height="556"
        alt={imageAlt}
        src={imageSrc}
      />
    </div>
  );
}

// components/HomePage/HomeHero.vue
<template>
  <div class="w-full h-[50vh] rounded-3xl relative group/plantation overflow-hidden">
    <div
      class="absolute z-[1] top-1/2 max-sm:p-5 max-sm:w-full -translate-y-1/2 left-1/2 -translate-x-1/2 flex flex-col gap-y-2 sm:gap-y-4"
    >
      <h1 class="text-neutral-50 text-4xl lg:text-6xl lg:max-w-[46.5rem] font-pally font-medium">
        <span class="text-primary-200">Éducation Écologique</span> pour un Terrain Confus
      </h1>
      <p class="text-neutral-50 lg:max-w-[41.5rem] text-lg lg:text-xl">
        Découvrez comment protéger notre environnement en apprenant les bonnes pratiques pour la conservation des sols,
        la gestion de l'eau et la préservation de la biodiversité.
      </p>
    </div>
    <NuxtImg
      preload
      class="rounded-3xl size-full object-cover brightness-[0.45] group-hover/plantation:scale-105 transition-transform duration-300"
      width="1336"
      height="556"
      alt="Image de présentation"
      src="/plantation.webp"
    />
  </div>
</template>

<script setup></script>
